import { useState } from 'react';
import { Check, KeyRound, Pencil, Plus, Trash2, X } from 'lucide-react';
import { authClient } from '@/lib/auth/client';
import {
  deriveDeviceName,
  formatPasskeyDate,
  isPasskeySupported,
  passkeyError,
} from '@/lib/auth/passkey';

const CARD_STYLE: React.CSSProperties = {
  background: 'var(--color-pt-surface)',
  border: '1px solid var(--color-pt-border)',
  borderRadius: 12,
  padding: '20px 20px',
};

const DESC_STYLE: React.CSSProperties = {
  fontSize: 12,
  color: 'var(--color-pt-text-3)',
  margin: '0 0 14px',
  lineHeight: 1.5,
};

const ROW_BUTTON_STYLE: React.CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 4,
  padding: '6px 8px',
  borderRadius: 7,
  border: '1px solid var(--color-pt-border)',
  background: 'var(--color-pt-surface)',
  fontSize: 12,
  fontWeight: 600,
  flexShrink: 0,
};

export function PasskeySecurityPanel() {
  // `useListPasskeys` is generated by the passkey client plugin from its `listPasskeys` atom.
  const { data: passkeys, isPending, refetch } = authClient.useListPasskeys();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState<{ id: string; name: string } | null>(null);
  const supported = isPasskeySupported();

  async function handleAdd() {
    setError(null);
    setBusy(true);
    try {
      const result = await authClient.passkey.addPasskey({ name: deriveDeviceName() });
      if (result?.error) {
        setError(passkeyError(result.error, 'register'));
      } else {
        refetch();
      }
    } catch (err) {
      setError(passkeyError(err, 'register'));
    } finally {
      setBusy(false);
    }
  }

  async function handleRemove(id: string) {
    setError(null);
    setBusy(true);
    try {
      const result = await authClient.passkey.deletePasskey({ id });
      if (result?.error) {
        setError(result.error.message ?? 'Could not remove that passkey. Please try again.');
      } else {
        refetch();
      }
    } catch {
      setError('Could not remove that passkey. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  async function handleRename() {
    if (!editing) return;
    const name = editing.name.trim();
    if (!name) return;
    setError(null);
    setBusy(true);
    try {
      const result = await authClient.passkey.updatePasskey({ id: editing.id, name });
      if (result?.error) {
        setError(result.error.message ?? 'Could not rename that passkey. Please try again.');
      } else {
        setEditing(null);
        refetch();
      }
    } catch {
      setError('Could not rename that passkey. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  const list = passkeys ?? [];

  return (
    <div style={{ ...CARD_STYLE, display: 'flex', flexDirection: 'column', gap: 8 }}>
      <p style={DESC_STYLE}>
        Passkeys let you sign in with your device&apos;s fingerprint, face, or PIN — no email link
        needed. They&apos;re tied to this device unless your platform syncs them (e.g. iCloud
        Keychain, Google Password Manager).
      </p>

      {error && (
        <div
          style={{
            margin: '0 0 8px',
            padding: '10px 12px',
            background: 'var(--color-pt-amber-soft)',
            border: '1px solid var(--color-pt-amber-border)',
            borderRadius: 8,
            fontSize: 12.5,
            color: 'var(--color-pt-amber-fg)',
          }}
        >
          {error}
        </div>
      )}

      {isPending ? (
        <p style={{ fontSize: 12.5, color: 'var(--color-pt-text-3)', margin: '4px 0' }}>
          Loading passkeys…
        </p>
      ) : list.length === 0 ? (
        <p style={{ fontSize: 12.5, color: 'var(--color-pt-text-3)', margin: '4px 0' }}>
          No passkeys registered yet. Add one to sign in faster next time.
        </p>
      ) : (
        <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 8 }}>
          {list.map((pk) => (
            <li
              key={pk.id}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                padding: '10px 12px',
                borderRadius: 8,
                border: '1px solid var(--color-pt-border)',
                background: 'var(--color-pt-surface-mut)',
              }}
            >
              <KeyRound
                size={15}
                strokeWidth={2}
                style={{ color: 'var(--color-pt-accent-fg)', flexShrink: 0 }}
              />
              {editing?.id === pk.id ? (
                <>
                  <input
                    value={editing.name}
                    onChange={(e) => setEditing({ id: pk.id, name: e.target.value })}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') void handleRename();
                      if (e.key === 'Escape') setEditing(null);
                    }}
                    autoFocus
                    aria-label="Passkey name"
                    style={{
                      flex: 1,
                      minWidth: 0,
                      padding: '5px 8px',
                      borderRadius: 6,
                      border: '1px solid var(--color-pt-border)',
                      background: 'var(--color-pt-surface)',
                      color: 'var(--color-pt-text)',
                      fontSize: 13,
                      outline: 'none',
                    }}
                  />
                  <button
                    type="button"
                    onClick={() => void handleRename()}
                    disabled={busy || !editing.name.trim()}
                    aria-label="Save passkey name"
                    style={{
                      ...ROW_BUTTON_STYLE,
                      color: 'var(--color-pt-accent-fg)',
                      cursor: busy ? 'not-allowed' : 'pointer',
                      opacity: busy || !editing.name.trim() ? 0.5 : 1,
                    }}
                  >
                    <Check size={13} strokeWidth={2.5} />
                  </button>
                  <button
                    type="button"
                    onClick={() => setEditing(null)}
                    disabled={busy}
                    aria-label="Cancel rename"
                    style={{
                      ...ROW_BUTTON_STYLE,
                      color: 'var(--color-pt-text-3)',
                      cursor: busy ? 'not-allowed' : 'pointer',
                    }}
                  >
                    <X size={13} strokeWidth={2.5} />
                  </button>
                </>
              ) : (
                <>
                  <span style={{ flex: 1, minWidth: 0 }}>
                    <span
                      style={{
                        display: 'block',
                        fontSize: 13,
                        fontWeight: 600,
                        color: 'var(--color-pt-text)',
                      }}
                    >
                      {pk.name || 'Passkey'}
                    </span>
                    {pk.createdAt && (
                      <span style={{ fontSize: 11.5, color: 'var(--color-pt-text-3)' }}>
                        Added {formatPasskeyDate(pk.createdAt)}
                      </span>
                    )}
                  </span>
                  <button
                    type="button"
                    onClick={() => {
                      setError(null);
                      setEditing({ id: pk.id, name: pk.name || 'Passkey' });
                    }}
                    disabled={busy}
                    aria-label={`Rename ${pk.name || 'passkey'}`}
                    style={{
                      ...ROW_BUTTON_STYLE,
                      color: 'var(--color-pt-text-2)',
                      cursor: busy ? 'not-allowed' : 'pointer',
                      opacity: busy ? 0.5 : 1,
                    }}
                  >
                    <Pencil size={13} strokeWidth={2} />
                    Rename
                  </button>
                  <button
                    type="button"
                    onClick={() => handleRemove(pk.id)}
                    disabled={busy}
                    aria-label={`Remove ${pk.name || 'passkey'}`}
                    style={{
                      ...ROW_BUTTON_STYLE,
                      color: 'var(--color-pt-red)',
                      cursor: busy ? 'not-allowed' : 'pointer',
                      opacity: busy ? 0.5 : 1,
                    }}
                  >
                    <Trash2 size={13} strokeWidth={2} />
                    Remove
                  </button>
                </>
              )}
            </li>
          ))}
        </ul>
      )}

      {!supported && (
        <p style={{ fontSize: 12.5, color: 'var(--color-pt-text-3)', margin: '4px 0' }}>
          This browser doesn&apos;t support passkeys, so one can&apos;t be added here.
        </p>
      )}

      <button
        type="button"
        onClick={handleAdd}
        disabled={busy || !supported}
        hidden={!supported}
        style={{
          marginTop: 4,
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 6,
          alignSelf: 'flex-start',
          padding: '9px 14px',
          borderRadius: 8,
          border: '1.5px solid var(--color-pt-accent-border)',
          background: 'var(--color-pt-accent-soft)',
          color: 'var(--color-pt-accent-fg)',
          fontSize: 13,
          fontWeight: 600,
          cursor: busy ? 'not-allowed' : 'pointer',
          opacity: busy ? 0.5 : 1,
        }}
      >
        <Plus size={14} strokeWidth={2.5} />
        {busy ? 'Working…' : 'Add a passkey'}
      </button>
    </div>
  );
}
