import { useState } from 'react';
import { KeyRound, Plus, Trash2 } from 'lucide-react';
import { authClient } from '@/lib/auth/client';

const CARD_STYLE: React.CSSProperties = {
  background: 'var(--color-pt-surface)',
  border: '1px solid var(--color-pt-border)',
  borderRadius: 12,
  padding: '20px 20px',
};

const DESC_STYLE: React.CSSProperties = {
  fontSize: 12,
  color: 'var(--color-pt-text-3)',
  margin: '0 0 14px',
  lineHeight: 1.5,
};

/** Best-effort human label for the passkey created on this device. */
function deriveDeviceName(): string {
  const ua = navigator.userAgent;
  const os = /Windows/.test(ua)
    ? 'Windows'
    : /Macintosh|Mac OS/.test(ua)
      ? 'Mac'
      : /iPhone|iPad/.test(ua)
        ? 'iOS'
        : /Android/.test(ua)
          ? 'Android'
          : 'this device';
  const browser = /Edg\//.test(ua)
    ? 'Edge'
    : /Chrome\//.test(ua)
      ? 'Chrome'
      : /Firefox\//.test(ua)
        ? 'Firefox'
        : /Safari\//.test(ua)
          ? 'Safari'
          : 'Browser';
  return `${browser} on ${os}`;
}

function formatDate(value: string | Date): string {
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

export function PasskeySecurityPanel() {
  // `useListPasskeys` is generated by the passkey client plugin from its `listPasskeys` atom.
  const { data: passkeys, isPending, refetch } = authClient.useListPasskeys();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleAdd() {
    setError(null);
    setBusy(true);
    try {
      const result = await authClient.passkey.addPasskey({ name: deriveDeviceName() });
      if (result?.error) {
        setError(result.error.message ?? 'Could not register a passkey. Please try again.');
      } else {
        refetch();
      }
    } catch {
      // WebAuthn throws when the user dismisses or no authenticator is available.
      setError('Passkey setup was cancelled or is not available on this device.');
    } finally {
      setBusy(false);
    }
  }

  async function handleRemove(id: string) {
    setError(null);
    setBusy(true);
    try {
      const result = await authClient.passkey.deletePasskey({ id });
      if (result?.error) {
        setError(result.error.message ?? 'Could not remove that passkey. Please try again.');
      } else {
        refetch();
      }
    } catch {
      setError('Could not remove that passkey. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  const list = passkeys ?? [];

  return (
    <div style={{ ...CARD_STYLE, display: 'flex', flexDirection: 'column', gap: 8 }}>
      <p style={DESC_STYLE}>
        Passkeys let you sign in with your device&apos;s fingerprint, face, or PIN — no email link
        needed. They&apos;re tied to this device unless your platform syncs them (e.g. iCloud
        Keychain, Google Password Manager).
      </p>

      {error && (
        <div
          style={{
            margin: '0 0 8px',
            padding: '10px 12px',
            background: 'var(--color-pt-amber-soft)',
            border: '1px solid var(--color-pt-amber-border)',
            borderRadius: 8,
            fontSize: 12.5,
            color: 'var(--color-pt-amber-fg)',
          }}
        >
          {error}
        </div>
      )}

      {isPending ? (
        <p style={{ fontSize: 12.5, color: 'var(--color-pt-text-3)', margin: '4px 0' }}>
          Loading passkeys…
        </p>
      ) : list.length === 0 ? (
        <p style={{ fontSize: 12.5, color: 'var(--color-pt-text-3)', margin: '4px 0' }}>
          No passkeys registered yet. Add one to sign in faster next time.
        </p>
      ) : (
        <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 8 }}>
          {list.map((pk) => (
            <li
              key={pk.id}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                padding: '10px 12px',
                borderRadius: 8,
                border: '1px solid var(--color-pt-border)',
                background: 'var(--color-pt-surface-mut)',
              }}
            >
              <KeyRound size={15} strokeWidth={2} style={{ color: 'var(--color-pt-accent-fg)', flexShrink: 0 }} />
              <span style={{ flex: 1, minWidth: 0 }}>
                <span
                  style={{
                    display: 'block',
                    fontSize: 13,
                    fontWeight: 600,
                    color: 'var(--color-pt-text)',
                  }}
                >
                  {pk.name || 'Passkey'}
                </span>
                {pk.createdAt && (
                  <span style={{ fontSize: 11.5, color: 'var(--color-pt-text-3)' }}>
                    Added {formatDate(pk.createdAt)}
                  </span>
                )}
              </span>
              <button
                type="button"
                onClick={() => handleRemove(pk.id)}
                disabled={busy}
                aria-label={`Remove ${pk.name || 'passkey'}`}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 4,
                  padding: '6px 8px',
                  borderRadius: 7,
                  border: '1px solid var(--color-pt-border)',
                  background: 'var(--color-pt-surface)',
                  color: 'var(--color-pt-red)',
                  fontSize: 12,
                  fontWeight: 600,
                  cursor: busy ? 'not-allowed' : 'pointer',
                  opacity: busy ? 0.5 : 1,
                  flexShrink: 0,
                }}
              >
                <Trash2 size={13} strokeWidth={2} />
                Remove
              </button>
            </li>
          ))}
        </ul>
      )}

      <button
        type="button"
        onClick={handleAdd}
        disabled={busy}
        style={{
          marginTop: 4,
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 6,
          alignSelf: 'flex-start',
          padding: '9px 14px',
          borderRadius: 8,
          border: '1.5px solid var(--color-pt-accent-border)',
          background: 'var(--color-pt-accent-soft)',
          color: 'var(--color-pt-accent-fg)',
          fontSize: 13,
          fontWeight: 600,
          cursor: busy ? 'not-allowed' : 'pointer',
          opacity: busy ? 0.5 : 1,
        }}
      >
        <Plus size={14} strokeWidth={2.5} />
        {busy ? 'Working…' : 'Add a passkey'}
      </button>
    </div>
  );
}
